import numpy as np

print("--- Smart store  sales analyzer---")

# 1. Generation: 5 products (rows) and 4 weeks of sales data (columns)
# Random sales numbers between 50 and 500 units
np.random.seed(42) # Setting the seed ensures the same random numbers are generated every time
sales_data = np.random.randint(50, 500, size=(5,4))
print("\n1.weekly sales matrix (products x weeks):\n", sales_data)

# 2.Axis-wise opertion (Math)
# total sales across each week (column-wise sum -> axis = 0)
weekly_totals = np.sum(sales_data, axis = 0)
print("\n2. Total Sales per Week:", weekly_totals)

# total units sold product across all the  weeks (row-wise sum -> axis = 1)
product_totals = np.sum(sales_data, axis=1)
print("Total Units Sold per Product:", product_totals)

# finding the best performing product  index
best_product = np.argmax(product_totals)
print(f"-> Best Selling Product is at Index: {best_product}")

# 3. broadcasting (calculation revenue using base prices)
# Base prices for the  5 products
base_prices = np.array([120, 150, 90, 300, 150])

# reshape base_prices to be a column vector (5, 1) for broadcasting
prices_column = base_prices.reshape(-1, 1)

# Calculating revenue (Sales units * Price) using broadcasting
revenue_matrix = sales_data * prices_column
print("\n3. Revenue Matrix (Calculated via broadcasting):\n", revenue_matrix)

# total overall revenue generated by the store
total_store_revenue = np.sum(revenue_matrix)
print(f"\n-> grand total store revenue: ${total_store_revenue}")




